column_list = [("year", "academic_year"),
               ("unitid", "institution_id"),
               ("tuition1", "in_district_avg_tuition_full_time_undergraduate"),
               ("fee1", "in_district_fee_full_time_undergraduate"),
               ("tuition2", "in_state_avg_tuition_full_time_undergraduate"),
               ("fee2", "in_state_fee_full_time_undergraduate"),
               ("chg1at3", "published_in_district_tuition"),
               ("chg1af3", "published_in_district_fees"),
               ("chg1ay3", "published_in_district_tuition_and_fees"),
               ("chg2at3", "published_in_state_tuition"),
               ("chg2af3", "published_in_state_fees"),
               ("chg2ay3", "published_in_state_tuition_and_fees"),
               ("chg4ay3", "books"),
               ("chg5ay3", "room_and_board_on_campus"),
               ("chg6ay3", "transportation_and_misc_on_campus"),
               ("chg7ay3", "room_and_board_off_campus_not_with_family"),
               ("chg8ay3", "transportation_and_misc_off_campus_not_with_family"),
               ("chg9ay3", "transportation_and_misc_off_campus_with_family")]